"""Pre-built phishing email templates for social engineering campaigns.

Each template uses GoPhish template variables:
- {{.FirstName}} - Target's first name
- {{.LastName}} - Target's last name
- {{.Position}} - Target's position/title
- {{.Email}} - Target's email
- {{.From}} - Sender address
- {{.URL}} - Phishing link (auto-generated by GoPhish)
- {{.TrackingURL}} - Tracking pixel URL
- {{.Tracker}} - Full tracking pixel <img> tag
- {{.BaseURL}} - Base URL of the phishing server

Templates are in German as the primary use case targets DACH region.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class PhishTemplate:
    """A phishing email template definition."""

    key: str
    name: str
    category: str
    subject: str
    html: str
    text: str
    description: str


# ── Template Definitions ──────────────────────────────────────────

PHISH_TEMPLATES: dict[str, PhishTemplate] = {}


def _register(t: PhishTemplate) -> None:
    PHISH_TEMPLATES[t.key] = t


# ── IT Support / Password Reset ──────────────────────────────────

_register(PhishTemplate(
    key="it_password_reset",
    name="IT-Abteilung: Passwort-Reset erforderlich",
    category="IT Support",
    subject="[Aktion erforderlich] Ihr Passwort läuft in 24 Stunden ab",
    description="Gibt sich als interne IT-Abteilung aus und fordert zum Passwort-Reset auf.",
    html="""<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
<div style="background: #0078d4; padding: 20px; color: white;">
    <h2 style="margin:0;">IT-Abteilung</h2>
</div>
<div style="padding: 20px; border: 1px solid #ddd; border-top: none;">
    <p>Guten Tag {{.FirstName}} {{.LastName}},</p>

    <p>im Rahmen unserer Sicherheitsrichtlinien müssen alle Passwörter regelmäßig
    erneuert werden. Ihr aktuelles Passwort läuft in <strong>24 Stunden</strong> ab.</p>

    <p>Bitte setzen Sie Ihr Passwort über unser Self-Service-Portal zurück:</p>

    <div style="text-align: center; margin: 30px 0;">
        <a href="{{.URL}}" style="background: #0078d4; color: white; padding: 12px 30px;
           text-decoration: none; border-radius: 4px; font-weight: bold;">
            Passwort jetzt ändern
        </a>
    </div>

    <p style="color: #666; font-size: 13px;">
        Sollten Sie Ihr Passwort nicht innerhalb von 24 Stunden ändern,
        wird Ihr Account vorübergehend gesperrt. Bei Fragen wenden Sie
        sich an die IT-Hotline (Durchwahl 4711).
    </p>

    <p>Mit freundlichen Grüßen,<br>
    <strong>IT-Support Team</strong></p>
</div>
<div style="padding: 10px 20px; background: #f5f5f5; font-size: 11px; color: #999;">
    Dies ist eine automatische Benachrichtigung. Bitte antworten Sie nicht auf diese E-Mail.
</div>
{{.Tracker}}
</body>
</html>""",
    text="""Guten Tag {{.FirstName}} {{.LastName}},

im Rahmen unserer Sicherheitsrichtlinien müssen alle Passwörter regelmäßig
erneuert werden. Ihr aktuelles Passwort läuft in 24 Stunden ab.

Bitte setzen Sie Ihr Passwort über unser Self-Service-Portal zurück:
{{.URL}}

Sollten Sie Ihr Passwort nicht innerhalb von 24 Stunden ändern,
wird Ihr Account vorübergehend gesperrt.

Mit freundlichen Grüßen,
IT-Support Team""",
))


# ── Microsoft 365 / SharePoint ───────────────────────────────────

_register(PhishTemplate(
    key="m365_shared_document",
    name="Microsoft 365: Geteiltes Dokument",
    category="Cloud Services",
    subject="{{.FirstName}}, ein Dokument wurde mit Ihnen geteilt",
    description="Imitiert eine Microsoft 365 SharePoint-Benachrichtigung über ein geteiltes Dokument.",
    html="""<!DOCTYPE html>
<html>
<body style="font-family: 'Segoe UI', Arial, sans-serif; background: #f3f2f1; padding: 20px;">
<div style="max-width: 520px; margin: 0 auto; background: white; border-radius: 4px; overflow: hidden;">
    <div style="padding: 20px 24px; border-bottom: 1px solid #edebe9;">
        <img alt="Microsoft" style="height: 24px;" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PHJlY3QgeD0iMSIgeT0iMSIgd2lkdGg9IjkiIGhlaWdodD0iOSIgZmlsbD0iI2YyNTAyMiIvPjxyZWN0IHg9IjExIiB5PSIxIiB3aWR0aD0iOSIgaGVpZ2h0PSI5IiBmaWxsPSIjN2ZiYTAwIi8+PHJlY3QgeD0iMSIgeT0iMTEiIHdpZHRoPSI5IiBoZWlnaHQ9IjkiIGZpbGw9IiMwMGE0ZWYiLz48cmVjdCB4PSIxMSIgeT0iMTEiIHdpZHRoPSI5IiBoZWlnaHQ9IjkiIGZpbGw9IiNmZmI5MDAiLz48L3N2Zz4=">
    </div>
    <div style="padding: 24px;">
        <p style="font-size: 20px; font-weight: 600; margin: 0 0 16px 0; color: #323130;">
            Dokument geteilt
        </p>
        <p style="color: #605e5c; margin: 0 0 20px 0;">
            <strong>Geschäftsleitung</strong> hat die Datei
            <em>"Jahresplanung_2026_VERTRAULICH.xlsx"</em> mit Ihnen geteilt.
        </p>

        <div style="text-align: center; margin: 24px 0;">
            <a href="{{.URL}}" style="background: #0078d4; color: white; padding: 10px 24px;
               text-decoration: none; border-radius: 3px; font-size: 14px; font-weight: 600;">
                Dokument öffnen
            </a>
        </div>

        <p style="font-size: 12px; color: #a19f9d; margin: 20px 0 0 0;">
            Microsoft respektiert Ihre Privatsphäre. Lesen Sie unsere
            Datenschutzerklärung.
        </p>
    </div>
</div>
{{.Tracker}}
</body>
</html>""",
    text="""Dokument geteilt

Geschäftsleitung hat die Datei "Jahresplanung_2026_VERTRAULICH.xlsx" mit Ihnen geteilt.

Dokument öffnen: {{.URL}}

Microsoft respektiert Ihre Privatsphäre.""",
))


# ── Bewerbung / HR ───────────────────────────────────────────────

_register(PhishTemplate(
    key="hr_application",
    name="Bewerbung: Neue Unterlagen eingegangen",
    category="HR / Personal",
    subject="Bewerbung für die Stelle als Senior Developer – Unterlagen zur Prüfung",
    description="Gefälschte Bewerbung mit Link zu 'Unterlagen'. Zielt auf HR/Personalabteilung.",
    html="""<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
<div style="padding: 20px;">
    <p>Sehr geehrte Damen und Herren,</p>

    <p>mit großem Interesse habe ich Ihre Stellenausschreibung auf StepStone
    gelesen und bewerbe mich hiermit für die ausgeschriebene Position.</p>

    <p>Meine vollständigen Bewerbungsunterlagen (Lebenslauf, Zeugnisse und
    Arbeitsproben) habe ich für Sie online bereitgestellt, da die Dateien
    für einen E-Mail-Anhang zu groß sind:</p>

    <div style="text-align: center; margin: 25px 0;">
        <a href="{{.URL}}" style="background: #28a745; color: white; padding: 12px 30px;
           text-decoration: none; border-radius: 4px; font-weight: bold;">
            Bewerbungsunterlagen herunterladen
        </a>
    </div>

    <p>Ich freue mich auf Ihre Rückmeldung und stehe für ein persönliches
    Gespräch gerne zur Verfügung.</p>

    <p>Mit freundlichen Grüßen,<br>
    <strong>Thomas Weber</strong><br>
    Tel.: 0151-12345678<br>
    thomas.weber@gmail.com</p>
</div>
{{.Tracker}}
</body>
</html>""",
    text="""Sehr geehrte Damen und Herren,

mit großem Interesse habe ich Ihre Stellenausschreibung auf StepStone
gelesen und bewerbe mich hiermit für die ausgeschriebene Position.

Meine vollständigen Bewerbungsunterlagen (Lebenslauf, Zeugnisse und
Arbeitsproben) habe ich für Sie online bereitgestellt:

{{.URL}}

Ich freue mich auf Ihre Rückmeldung.

Mit freundlichen Grüßen,
Thomas Weber""",
))


# ── Lieferant / Rechnung ─────────────────────────────────────────

_register(PhishTemplate(
    key="invoice_supplier",
    name="Lieferant: Offene Rechnung",
    category="Finanzen",
    subject="Zahlungserinnerung – Rechnung RE-2026-03-1847 überfällig",
    description="Gefälschte Zahlungserinnerung eines Lieferanten. Zielt auf Buchhaltung/Geschäftsleitung.",
    html="""<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
<div style="border: 1px solid #ddd; border-radius: 4px; overflow: hidden;">
    <div style="background: #e74c3c; padding: 15px 20px; color: white;">
        <strong>⚠ Zahlungserinnerung</strong>
    </div>
    <div style="padding: 20px;">
        <p>Sehr geehrte Damen und Herren,</p>

        <p>leider konnten wir für die nachfolgende Rechnung noch keinen
        Zahlungseingang feststellen:</p>

        <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
            <tr style="background: #f8f9fa;">
                <td style="padding: 8px; border: 1px solid #ddd;"><strong>Rechnungsnr.</strong></td>
                <td style="padding: 8px; border: 1px solid #ddd;">RE-2026-03-1847</td>
            </tr>
            <tr>
                <td style="padding: 8px; border: 1px solid #ddd;"><strong>Betrag</strong></td>
                <td style="padding: 8px; border: 1px solid #ddd;">€ 4.287,50</td>
            </tr>
            <tr style="background: #f8f9fa;">
                <td style="padding: 8px; border: 1px solid #ddd;"><strong>Fällig seit</strong></td>
                <td style="padding: 8px; border: 1px solid #ddd; color: #e74c3c;"><strong>14 Tagen</strong></td>
            </tr>
        </table>

        <p>Die Rechnung und Zahlungsdetails finden Sie hier:</p>

        <div style="text-align: center; margin: 20px 0;">
            <a href="{{.URL}}" style="background: #e74c3c; color: white; padding: 12px 30px;
               text-decoration: none; border-radius: 4px; font-weight: bold;">
                Rechnung einsehen & bezahlen
            </a>
        </div>

        <p style="font-size: 13px; color: #666;">
            Sollte sich Ihre Zahlung mit dieser Erinnerung gekreuzt haben,
            betrachten Sie dieses Schreiben als gegenstandslos.
        </p>

        <p>Mit freundlichen Grüßen,<br>
        <strong>TechSupply GmbH</strong><br>
        Buchhaltung</p>
    </div>
</div>
{{.Tracker}}
</body>
</html>""",
    text="""Zahlungserinnerung

Sehr geehrte Damen und Herren,

leider konnten wir für die Rechnung RE-2026-03-1847 (€ 4.287,50)
noch keinen Zahlungseingang feststellen. Die Rechnung ist seit 14 Tagen überfällig.

Rechnung einsehen: {{.URL}}

Sollte sich Ihre Zahlung mit dieser Erinnerung gekreuzt haben,
betrachten Sie dieses Schreiben als gegenstandslos.

Mit freundlichen Grüßen,
TechSupply GmbH – Buchhaltung""",
))


# ── Paket / Lieferung ────────────────────────────────────────────

_register(PhishTemplate(
    key="delivery_notification",
    name="DHL: Paket konnte nicht zugestellt werden",
    category="Logistik",
    subject="Ihre Sendung konnte nicht zugestellt werden – Aktion erforderlich",
    description="Gefälschte DHL-Benachrichtigung über fehlgeschlagene Zustellung.",
    html="""<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; background: #f5f5f5;">
<div style="background: #ffcc00; padding: 15px 20px;">
    <strong style="font-size: 18px; color: #333;">📦 DHL Paketservice</strong>
</div>
<div style="background: white; padding: 20px; border: 1px solid #ddd; border-top: none;">
    <p>Guten Tag {{.FirstName}} {{.LastName}},</p>

    <p>Ihre Sendung mit der Nummer <strong>JJD00012345678901234</strong>
    konnte heute leider nicht zugestellt werden, da niemand anzutreffen war.</p>

    <p>Bitte wählen Sie einen neuen Zustelltermin oder eine Packstation
    in Ihrer Nähe:</p>

    <div style="text-align: center; margin: 25px 0;">
        <a href="{{.URL}}" style="background: #d40511; color: white; padding: 12px 30px;
           text-decoration: none; border-radius: 4px; font-weight: bold;">
            Neuen Zustelltermin wählen
        </a>
    </div>

    <p style="font-size: 12px; color: #999;">
        Die Sendung wird 7 Tage in unserem Depot aufbewahrt und anschließend
        an den Absender zurückgeschickt.
    </p>
</div>
{{.Tracker}}
</body>
</html>""",
    text="""DHL Paketservice

Guten Tag {{.FirstName}} {{.LastName}},

Ihre Sendung JJD00012345678901234 konnte heute nicht zugestellt werden.

Neuen Zustelltermin wählen: {{.URL}}

Die Sendung wird 7 Tage aufbewahrt und anschließend zurückgeschickt.""",
))


def list_templates() -> dict[str, PhishTemplate]:
    """Return all available phishing templates."""
    return PHISH_TEMPLATES


def get_template(key: str) -> PhishTemplate | None:
    """Get a phishing template by key."""
    return PHISH_TEMPLATES.get(key)
